#!/usr/bin/python
from subprocess import call
import json
import sys
import os

windows=[]
with open(os.environ['HOME']+'/.tmux-windows.json') as json_str:
    data = json.load(json_str)

if len(data['windows'])==0:
    print "No windows specified in tmux-windows.json."
    sys.exit(1)

windows = data['windows']

call(["tmux","new","-s",sys.argv[1],"-d"])

i=0
for window in windows:
    workdir_arg = ""
    if 'workdir' in window:
        workdir_arg = "-c "+window['workdir']

    command_arg = ""
    if 'command' in window:
        command_arg = window['command']

    cmd = "tmux new-window -dk -t "+str(i)+" -n "+window['name']+" "+workdir_arg+" '"+command_arg+"'"

    call(cmd, shell=True)

    i+=1

call(["tmux","attach","-t",sys.argv[1]])

sys.exit(0)
